jobs:
  run:
    name: Build
    runs-on: ubuntu-20.04

    steps:
      - name: Start Up
        uses: actions/checkout@v2
      - name: Download Prerequisites
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./check/verify

name: Workflow

on:
  schedule:
    - cron: "20 2/3 * * *"
